when:
  - event: push
  - event: pull_request
  - event: manual

matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6

steps:
  - name: test
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements.txt
      - pip install nose coverage warcat youtube-dl
      - pip install . --no-dependencies
      - nosetests --with-coverage --cover-package=wpull --cover-branches